# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test
      
    - name: Coverage Robot Action
      # You may pin to the exact commit or the version.
      # uses: coverage-robot/action@453c16688719c0d30d4162737a44d0f0a83a014b
      uses: coverage-robot/action@v1.0.0
      with:
        # Multi-line selection of coverage files to upload
        files: |
            ./coverage.xml
        token:  ${{ secrets.COVERAGE_TOKEN }}
        # The GitHub token used to communicate with the Github API
